name: Build and Deploy to gh-pages.

on:
    push:
        branches:
            - 'main'

    pull_request:
        branches:
            - '**'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            # if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'site')) }}
            #- name: check
            #  # if: ${{ (github.event.pull_request.merged == true) && (github.ref == 'refs/heads/main') }}
            #  run: echo "merged, and we are in main!"

            - name: lets see

              run: echo ${{ github.event.pull_request.merged }}

            - name: lets see another
              run: echo ${{ github.ref }}

            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.19.1

            - name: Install deps
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Run units
              uses: borales/actions-yarn@v4
              with:
                  cmd: test

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: production-build
                  path: ./dist
                  if-no-files-found: error

    deploy:
        name: Deploy to staging
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Check
              run: ls -a

            - name: Download artifact
              uses: actions/download-artifact@master
              with:
                   name: production-build
                   path: .

            - name: Specify branch name
              run: echo "BRANCH_NAME=$(echo ${{ github.head_ref || github.ref_name }} | sed -r 's/[/]+/-/g')" >> $GITHUB_ENV

            - name: Define destination folder
              uses: haya14busa/action-cond@v1
              id: destinationFolder
              with:
                  cond: ${{ github.ref == 'refs/heads/main' }}
                  if_true: '.'
                  if_false: ${{ env.BRANCH_NAME }}

            - name: Check
              run: ls -a


            - name: Deploy to github pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  destination_dir: ${{ steps.destinationFolder.outputs.value }}
                  publish_branch: staging
                  keep_files: true

            - name: Check
              run: |
                 ls -a
                 cd ../
                 ls -a
                 cd ../
                 ls -a
    clean:
        name: Remove folder after deploy
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
              run: ls -a



            #- name: Optional - delete folder after merge
            #  id: deleteFolder
            #  if: github.ref == 'refs/heads/main'
            #  run: | rm -f \
            #      .github/
