name: Deploy

on:
    push:
        branches:
            - '**'        # matches every branch
            # - '!main'

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.19.1

            - name: Install deps
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Run units
              uses: borales/actions-yarn@v4
              with:
                  cmd: test

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Upload build
              uses: actions/upload-artifact@v3
              with:
                  name: production-build
                  path: ./build/dist
                  if-no-files-found: error

    deploy:
        name: Deploy to gh-pages test-stand
        needs: build
        runs-on: ubuntu-latest
        # if: github.ref == 'refs/heads/main'

        steps:
            - name: Download artifact
              uses: actions/upload-artifact@v3
              with:
                  name: production-build
                  path: ./dist
                  if-no-files-found: error

            - name: Deploy to gh pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build/dist