name: Deploy

on:
    push:
        branches:
            - '**'        # matches every branch
            # - '!main'

env:
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14.19.1

            - name: Install deps
              uses: borales/actions-yarn@v4
              with:
                  cmd: install

            - name: Run units
              uses: borales/actions-yarn@v4
              with:
                  cmd: test

            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: production-build
                  path: ./dist
                  if-no-files-found: error
    # echo "feat/ISC-7/test/gay" | sed -r 's/[/]+/-/g'
    deploy:
        env:

        name: Deploy to gh-pages test-stand
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Log
              run:
                  ls -a

            - name: Download artifact
              uses: actions/download-artifact@master
              with:
                   name: production-build
                   path: .
                   if-no-files-found: error

            - name: Deploy to gh pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: .
                  destination_dir: echo $BRANCH_NAME | sed -r 's/[/]+/-/g'  # "$BRANCH_NAME | sed -r 's/[/]+/-/g'"