on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]



jobs:
    rebuild:
        runs-on: ubuntu-latest
        steps:

            -   uses: khan/pull-request-comment-trigger@v1.1.0
                id: check
                with:
                    trigger: '@rebuild'
                    reaction: rocket
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

            -   name: On comment
                if: steps.check.outputs.triggered == 'true'
                run: echo ${{ github.ref_name }}

