on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    rebuild:
        runs-on: ubuntu-latest
        steps:

            -   name: Check message
                uses: khan/pull-request-comment-trigger@v1.1.0
                id: check
                with:
                    trigger: '-rebuild-'
                    reaction: rocket
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

            -   name: Rebuild previous
                if: steps.check.outputs.triggered == 'true'
                uses: peter-evans/repository-dispatch@v1
                with:
                    token: ${{ secrets.PAT }}
                    event-type: my-event
